### ISSUE TITLE
Issues Bugs and Defects

### ISSUE THREAD

**Issue by AlyssaJia** [Jonah-Roesler-Edu/ABJ-SoftSol_A02#16]
Issues/Bugs/Defects are being tracked in GitHub and assigned appropriately. Comments appropriate to the status change, remediation and related are present. Git commit comments reference the Issues Bugs and Defects.Bugs/Defects are fixed from previous iteration

**Comment by AlyssaJia** [comment]
Currently Server cant read files except with an absolute path.

**Comment by Jonah-Roesler-Edu** [comment]
System can now read and write but only with absolute paths
