### ISSUE TITLE
Task Page problems

### ISSUE THREAD

**Issue by AlyssaJia** [Jonah-Roesler-Edu/ABJ-SoftSol_A02#36]
I made imported the task class and had the creation of the table work properly but creating a row in the table won't work and I don't know how to fix that, as well as the rest of it sorry .
Its all in Iteration02_Messy03

**Comment by Jonah-Roesler-Edu** [comment]
Fixed the task page so that it creates the table and rows properly. 
had something to do with the mapping in hibernate.cfg.xml
